### PR TITLE
Added DNS helper popover

### LINKED ISSUE #27: Add helper tooltip
The DNS validation page should have a question mark helper tooltip. It is my understanding that @bradleyrichter has compiled a list of popular hosts and their DNS help pages that we can link to.

### PR DESCRIPTION
**Pull request by jkup**
Fix #27

Auditors @bradleyrichter @ayumi @bsclifton 

Alright. Thanks to @ayumi I got this working. How does it look to you all?

screen shot 2016-12-12 at 9 18 25 pm

### CODE REVIEW

**Comment by bradleyrichter** [comment]
@jkup Can you make it larger so it overlaps other things like the Copy to Clipboard button?

It still needs a shadow, and the orange links seem a bit heavy. I know we have this on brave.com but we don't have a page with a table of links. Maybe grey with orange on mouse-over?

**Comment by jkup** [comment]
@bradleyrichter how is the new screenshot?

**Comment by bradleyrichter** [comment]
almost there....

- grey close button?
- wider if possible. But looks good for now.

**Comment by bsclifton** [comment]
Just tested it out, looks great! :smile:

**Pull request merged**
